# This docker-compose.yml is only used when running the kartta app by itself
# from this directory for development purposes.  It's not use when running
# kartta as part of the Kartta Labs suite (https://github.com/kartta-labs/Project).

version: '3.3'
services:
  kartta:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["/bin/sh", "/kartta/docker-launch.sh"]
    volumes:
      - .:/kartta
    ports:
      - "8000:8000"
