APP_PREFIX: ""
APP_HOME_URL: "http://localhost:8000"
SHARED_ASSETS_PATH: "/assets"
TILESERVER_ANTIQUE_JSON: "https://vectortiles.example.org/capabilities/antique.json"
INITIAL_YEAR: "1900"
SITE_NAME: "Kartta Labs"
CONTACT_EMAIL: "kartta@example.com"
