APP_PREFIX: ""
APP_HOME_URL: "http://localhost:8000"
SHARED_ASSETS_PATH: "/assets"
TILESERVER_ANTIQUE_JSON: "https://vectortiles.example.org/capabilities/antique.json"
MBGL_TILESERVER_ANTIQUE_JSON: "https://vectortiles.example.org/capabilities/antique.json"
INITIAL_YEAR: "1940"
INITIAL_ZOOM: "15"
INITIAL_LAT: "40.74096"
INITIAL_LON: "-73.99254"
SITE_NAME: "Kartta Labs"
CONTACT_EMAIL: "kartta@example.com"
EDITOR_URL: "http://localhost:8000/e"
NOTER_URL: "http://localhost:8000/nf"
NOTER_API_URL: "http://localhost:8000/nb"
